### PR TITLE
test(material): add basic material system tests

### PR DESCRIPTION
**Pull request by simonihmig**

### CODE REVIEW

**Comment by simonihmig** [comment]
> This PR made me wonder if we can test if resources are properly cleaned up after removal

Like what exactly? Something beyond what this test does? https://github.com/kaliber5/ecsy-babylon/pull/56/files#diff-b3ed34b792715a5580d614346ebe0ea5R86-R105

**Comment by nickschot** [comment]
That test checks if the material is `null` not if the resource (as in the babylon resource) actually was cleaned up, something we ran into multiple times during development (memory leaks).

It'd basically test whatever happens "inside" `entity.remove() or removeComponent()`

**Comment by simonihmig** [comment]
> That test checks if the material is null not if the resource (as in the babylon resource) actually was cleaned up

In what way is this different? I am fetching the named material from Babylon's scene, so if the material resource would still exist, it would return it, right? In what other way could you test that the material is gone?

**Comment by nickschot** [comment]
🤦‍♂ I missed the bit where you fetched it from the scene. That should indeed be enough. I don't think the babylon resource have a (public) api for checking if it was disposed of. There is an `onDispose` hook which might be useful for a system test (or indeed do it the way you did here).

**Pull request merged**
